---
- name: Configure Elk VM with Docker
  hosts: elkservers
  remote_user: elk
  become: true
  tasks:
  - name: Install docker.io
    apt:
      force_apt_get: yes
      name: docker.io
      state: present
  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present
  - name: Install Docker python module
    pip:
      name: docker
      state: present
  - name: Increase virtual memory
    command: sysctl -w vm.max_map_count=262144
  - name: Increase virtual memory on restart
    shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf
  - name: download and launch a docker elk container
    docker_container:
      name: elk
      image: sebp/elk
      state: started
      restart_policy: always
      published_ports:
        - 5601:5601
        - 9200:9200
        - 5044:5044
